version: '3.9'

networks:
  manage-food-network:
  # default:
  #   name: manage-food-network

services:
  manage-food-api:
    image: ${DOCKER_REGISTRY-}managefoodapi
    container_name: manage-food-API
    build:
      context: .
      dockerfile: ManageFood.API/Dockerfile
    depends_on:
      - manage-food-db
    links:
      - manage-food-db
    networks:
      - manage-food-network

  manage-food-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: manage-food-DB
    hostname: sql-server
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
      - MSSQL_USER=sa
      - MSSQL_SA_PASSWORD=ManageFood__Password
    ports:
      - 8055:1433
    expose:
      - 8055
    networks:
      - manage-food-network
